-- Insertar vacantes de ejemplo para testing
INSERT INTO job_positions (
  title,
  slug,
  department,
  location,
  contract_type,
  working_hours,
  salary_range,
  description,
  requirements,
  responsibilities,
  status,
  is_featured,
  display_order,
  published_at
) VALUES 
(
  'Asesor Fiscal Senior',
  'asesor-fiscal-senior',
  'Fiscal',
  'Barcelona',
  'Indefinido',
  'Completa',
  '45.000€ - 55.000€',
  'Buscamos un Asesor Fiscal Senior con experiencia en asesoramiento integral a empresas y particulares. Formarás parte de un equipo dinámico y trabajarás en proyectos desafiantes.',
  ARRAY['Grado en Derecho, ADE o similar', 'Mínimo 5 años de experiencia en asesoría fiscal', 'Conocimientos avanzados de normativa fiscal española', 'Dominio de herramientas de gestión fiscal'],
  ARRAY['Asesoramiento fiscal integral a cartera de clientes', 'Elaboración y revisión de declaraciones fiscales', 'Planificación fiscal estratégica', 'Representación ante la administración tributaria'],
  'published',
  true,
  1,
  NOW()
),
(
  'Abogado Laboralista',
  'abogado-laboralista',
  'Laboral',
  'Madrid',
  'Indefinido',
  'Completa',
  '40.000€ - 50.000€',
  'Incorporación inmediata de Abogado especializado en Derecho Laboral para asesorar a nuestros clientes en relaciones laborales, negociación colectiva y litigios.',
  ARRAY['Licenciatura en Derecho', 'Mínimo 3 años de experiencia en derecho laboral', 'Conocimiento profundo del Estatuto de los Trabajadores', 'Experiencia en litigios laborales'],
  ARRAY['Asesoramiento en relaciones laborales', 'Redacción de contratos y acuerdos', 'Gestión de despidos y sanciones', 'Representación en juicios laborales'],
  'published',
  true,
  2,
  NOW()
),
(
  'Contable Junior',
  'contable-junior',
  'Contabilidad',
  'Híbrido',
  'Indefinido',
  'Completa',
  '25.000€ - 30.000€',
  'Oportunidad para recién titulados o profesionales con poca experiencia que quieran desarrollar su carrera en contabilidad dentro de una firma de prestigio.',
  ARRAY['Grado en Administración y Dirección de Empresas o Economía', '1-2 años de experiencia en contabilidad', 'Conocimientos de A3 o ContaPlus', 'Nivel medio de Excel'],
  ARRAY['Registro de operaciones contables', 'Conciliaciones bancarias', 'Elaboración de cierres mensuales', 'Apoyo en auditorías internas'],
  'published',
  false,
  3,
  NOW()
),
(
  'Consultor Legal Corporativo',
  'consultor-legal-corporativo',
  'Legal',
  'Barcelona',
  'Indefinido',
  'Completa',
  '50.000€ - 65.000€',
  'Buscamos un profesional con visión estratégica para asesorar a grandes empresas en operaciones corporativas, fusiones, adquisiciones y reestructuraciones.',
  ARRAY['Licenciatura en Derecho', 'Mínimo 7 años de experiencia en M&A', 'Inglés nivel avanzado', 'Experiencia en transacciones internacionales'],
  ARRAY['Due diligence legal en operaciones M&A', 'Asesoramiento en gobierno corporativo', 'Redacción y negociación de contratos complejos', 'Gestión de equipos multidisciplinares'],
  'published',
  true,
  4,
  NOW()
),
(
  'Becario en Tecnología e Innovación',
  'becario-tecnologia-innovacion',
  'Tecnología',
  'Remoto',
  'Prácticas',
  'Parcial',
  NULL,
  'Oportunidad de prácticas para estudiantes de últimos cursos o recién graduados que quieran aprender sobre transformación digital en el sector de servicios profesionales.',
  ARRAY['Estudiante o graduado en Ingeniería Informática o similar', 'Conocimientos básicos de desarrollo web', 'Interés en IA y automatización', 'Nivel medio de inglés'],
  ARRAY['Apoyo en proyectos de digitalización', 'Investigación de nuevas herramientas tecnológicas', 'Desarrollo de pequeñas funcionalidades', 'Documentación técnica'],
  'published',
  false,
  5,
  NOW()
)